---
- name: How to prompt for variables
  hosts: localhost
  gather_facts: no

  vars_prompt:
    - name: "yourpassword"  # Variable name to define
      prompt: "What is your password?" # Question to ask
      private: no
      ## do not reveal the password (optional)
      ## run this encryption method (optional)
      ## type the password twice (optional)
      ## this is the size of the RAND you'd like to have generated (optional)
      # salt: slappysquirrel88 # provide your own RAND (optional)
      ## default to this password (optional)

  tasks:
    - name: Print out the password
      debug:
        msg: "{{ yourpassword }}"
